
language: r
r:
  - 3.6.0
cache: packages
warnings_are_errors: false

env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

sudo: true
before_install:
  - mkdir -p ~/.R/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "CXX14 = g++-7 -fPIC" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars; fi
  - sudo apt-get install jags
  - sudo apt-get install r-cran-rjags
  - Rscript -e 'install.packages(c("bayesm","lattice","lme4","lmtest","R2jags","bayesplot","caret","GGally","ggplot2","hexbin","latex2exp","papeR","parallel","rstan","rstanarm"," sandwich","sqldf","coda"),dependencies = TRUE)'

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

r_packages:
  - covr
  - ggplot2
  - faraway
  - pander
  - pkgdown
  - rmarkdown

after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'pkgdown::build_site()'
  - tar -C .. -xf $PKG_TARBALL
  - rm -rf RTest.Rcheck
  - R CMD INSTALL .
  - Rscript -e 'devtools::install()'

deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
local_dir: "docs"
keep_history: true
on:
  branch: master

notifications:
  slack: aloidiasolutions:wK07bxfNlwQ5Biau7Brvh9O1
