
language: r
r:
  - 3.6.0
cache: packages
warnings_are_errors: false

env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

sudo: true
before_install:
  - mkdir -p ~/.R/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "CXX14 = g++-7 -fPIC" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars; fi
  - sudo apt-get install jags
  - sudo apt-get install r-cran-rjags

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

r_packages:
  - covr
  - ggplot2
  - faraway
  - pander
  - pkgdown
  - rmarkdown

after_success:
  - Rscript -e 'library(covr); codecov()'
  - tar -C .. -xf $PKG_TARBALL
  - rm -rf RTest.Rcheck
  - R CMD INSTALL .
  - Rscript -e 'devtools::install()'

notifications:
  slack: aloidiasolutions:wK07bxfNlwQ5Biau7Brvh9O1
