
language: r
r:
  - 3.5.0
cache: packages
warnings_are_errors: false

sudo: true
before_install:
  - sudo apt-get install jags
  - sudo apt-get install r-cran-rjags


repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

r_packages:
  - covr
  - ggplot2
  - faraway
  - pander
  - pkgdown

after_success:
  - Rscript -e 'library(covr); codecov()'
  - tar -C .. -xf $PKG_TARBALL
  - rm -rf RTest.Rcheck
  - R CMD INSTALL .
  - Rscript -e 'devtools::install()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: "docs"
  keep_history: true
  on:
    branch: master

notifications:
  slack: aloidiasolutions:wK07bxfNlwQ5Biau7Brvh9O1
